workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

include:
  - local: backend/.gitlab-ci.yml
  - local: toolkit/.gitlab-ci.yml
  - local: frontend/.gitlab-ci.yml
  - local: web_ide/.gitlab-ci.yml

stages:
  - lint
  - build
  - audit

default:
  interruptible: true
