workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
  - trigger

backend:
  stage: trigger
  trigger:
    include: backend/.gitlab-ci.yml
    strategy: depend

toolkit:
  stage: trigger
  trigger:
    include: toolkit/.gitlab-ci.yml
    strategy: depend

frontend:
  stage: trigger
  trigger:
    include: frontend/.gitlab-ci.yml
    strategy: depend

web_ide:
  stage: trigger
  trigger:
    include: web_ide/.gitlab-ci.yml
    strategy: depend
