/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AuthorName = string;
export type AuthorEmail = string;
export type NodeType = "function" | "pwd" | "pyiron_workflow_function" | "pyiron_core_node";
export type PythonImport = string | null;
export type Dependencies = string[] | null;
export type SourceCode = string;
export type SourceCodeHash = string;
export type Docstring = string;
export type AiDocstring = string;
export type Label = string | null;
export type Datatype = string | null;
export type Unit = string | null;
export type Quantity = string | null;

export interface NodeResponse {
  author_name: AuthorName;
  author_email: AuthorEmail;
  node_type: NodeType;
  python_import?: PythonImport;
  dependencies?: Dependencies;
  source_code: SourceCode;
  source_code_hash: SourceCodeHash;
  docstring: Docstring;
  ai_docstring: AiDocstring;
  inputs: Inputs;
  outputs: Outputs;
  [k: string]: unknown;
}
export interface Inputs {
  [k: string]: Annotation;
}
export interface Annotation {
  label?: Label;
  datatype?: Datatype;
  unit?: Unit;
  quantity?: Quantity;
  [k: string]: unknown;
}
export interface Outputs {
  [k: string]: Annotation;
}
